### ISSUE TITLE
Organize panels in project creation 

### ISSUE THREAD

**Issue by kauedesousa** [BioversityCostaRica/py3ClimMob#138]
3 can be 4 and 4 can be 3. This will give more room to selecting the template if needed

![image](https://user-images.githubusercontent.com/29840771/159919767-4b830282-e2d7-409e-bd86-7be114903114.png)

**Comment by BioversityCostaRica** [comment]
@kauedesousa, in that case we would have the same problem with the list of countries.

The list of templates always shows 8 items and if they are more it creates a scroll.

I have solved this by adding a space below the create project button to fit the size of the template list.

I have also organized so that the panels are seen in the same column.

![Screenshot_20220324_091057](https://user-images.githubusercontent.com/13785174/159950775-d07eace1-5b11-4aa2-a086-960220429136.png)
