### ISSUE TITLE
generate packages

### ISSUE THREAD

**Issue by BertaOrtiz** [BioversityCostaRica/py3ClimMob#204]
this needs a bit more of explanation. Why the number of packages can be changed? what does it mean "included"?

**Comment by kauedesousa** [comment]
Lets try this.

"ClimMob implements a balanced trial randomisation, meaning that all technologies are tested in the same proportions across the trial. However, in some cases you may not have access to all technologies in the same proportions (e.g. due to issues in seed multiplication). To account for this issue, ClimMob accepts unbalanced trials with some technologies being tested less than others, but at the same time trying to keep the consistence of the trial design. A minimum of five packages should be tested per technology."
